### ISSUE TITLE
controller names with _ are not mapped correctly.

### ISSUE THREAD

**Issue by tacman** [pankaj3399/stimulus-js#1]
This works in regular twig, but not using this library.

```twig

{% set _sc = 'audio_player' %}
                            <div {{ stimulus_controller(_sc, {
                                startingTrack: asset.url
                            }) }}>
</div>
```

if you change the name of the controller to something without an underscore, it works as expected.

                                 {% set _sc = 'audio' %}

The controller name is audio_player_controller.js

**Comment by tacman** [comment]
![image](https://github.com/pankaj3399/stimulus-js/assets/619585/b6489438-eef1-4f30-83ba-8723ed287bfb)

top one is php twig, second one (with underscores) is this library.

I thought there was a test for controller names with underscores.

**Comment by pankaj3399** [comment]
Fixed it here https://github.com/pankaj3399/stimulus-js/commit/7426194f22f0402fb9c9f3b93cda1d06a10d5da7
